[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyw?$'

[tool.isort]
profile = "black"
line_length = 120  # Match Black's line length
multi_line_output = 3

[tool.ruff]
line-length = 120  # Match Black's line length

[tool.ruff.lint]
select = ["E", "F", "W", "I"]  # Enable specific linting rules