<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <Target Name="InjectLicenseKey" BeforeTargets="Build">
    <PropertyGroup>
      <LicenseKey>$(SYNCFUSION_LICENSE_KEY)</LicenseKey>
    </PropertyGroup>
    <WriteLinesToFile
      File="wwwroot/appsettings.json"
      Lines='{"SyncfusionLicenseKey":"$(LicenseKey)"}'
      Overwrite="true" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.10" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
    <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Sinks.BrowserConsole" Version="8.0.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Syncfusion.Blazor.FileManager" Version="31.2.2" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="31.2.2" />
    <PackageReference Include="Syncfusion.Licensing" Version="31.2.2" />
  </ItemGroup>

</Project>
