name: On Push Create Package
on:
  push:
    branches:
      - main
      - try/*
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine setuptools
          pip install -r requirements.txt
      
      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel
      
      - name: Publish the artifact
        uses: actions/upload-artifact@v4
        with:
          name: filepi-packages
          path: dist/